### ISSUE TITLE
Add no_std support

### ISSUE THREAD

**Issue by hobofan** [vislyhq/stretch#10]
Would be great if `stretch` would have `#![no_std]` support to make it work on as many platforms as possible!

Luckily all `std` dependencies (except for `Vec`) are actually from `core`, so this should be doable.

If you want I can prepare a PR that adds conditional `no_std` support via a feature flag. Sadly for now the `no_std` variant will only work on nightly for now, as the `alloc` crate (required for `Vec`) is [unstable for now](https://doc.rust-lang.org/unstable-book/library-features/alloc.html).

**Comment by emilsjolander** [comment]
I think supporting no_std would be great! How much would have to change to support this, assuming we can use alloc crate? If it's not a huge change then feel free to show me in a PR 👍
