### ISSUE TITLE
Index trees

### ISSUE THREAD

**Issue by msiglreith** [vislyhq/stretch#17]
Hi, I'm currently evaluating the library for usage inside a UI framework as replacement for yoga.
`compute` returns a newly created `layout::Node` tree which mirrors the input `style::Node` tree if I understand it correctly. I would be great to have tighter coupling between those two trees. Ideally, being addressable by an index. This should also give room for reusing memory to avoid many small vec allocations. It might be also possible to decouple the `layout_cache` from the `layout::Node` and move into implementation details.
Drawback of this would be a slightly more complex API due to the need of an additional tree/graph struct managing the node tree.

In case there is interest for changes in this direction, I would glady take a stab at it!
Cheers, the crate looks great so far!

**Comment by emilsjolander** [comment]
I'm planning a bigger API re-write which will solve some of these things, it will more tightly couple style::Node and layout::Node as well as making the API more mutable to ensure we can do more efficient re-calculations when just one or two properties have changes in the tree. If you have any concrete ideas for a good design on this I'de love to see it.

**Comment by emilsjolander** [comment]
@msiglreith Let's continue the discussion here https://github.com/vislyhq/stretch/issues/18. I kicked it off with my current idea for the new API.

**Comment by msiglreith** [comment]
FYI I adjusted the API for my needs in my GUI library in my fork: https://github.com/msiglreith/stretch/tree/index-api
This is probably similar to the ongoing efforts in https://github.com/vislyhq/stretch/pull/25 just a bit more explicit.

## How does it look like
`basic` example: https://github.com/msiglreith/stretch/blob/index-api/examples/basic.rs#L5-L18

There is a global graph structure `Stretch` which holds all the data. It follows the ECS concept by separating data into multiple storages (https://github.com/msiglreith/stretch/blob/index-api/src/node.rs#L39-L47), otherwise works similar to other index based graph crates out there.

## Pros

- Easier to map layout compute output with the input graph as everything can be accessed directly via the NodeId
- Reduces the number dynamic allocations when layouting (small performance gains ~10% in the `complex` benchmark, but it's in the <1ms range anyway)

## Cons

- Less safe API as it's based on Ids (atm non-generational)
- Declaring a layout is more verbose

**Comment by emilsjolander** [comment]
This is interesting. Would you mind putting up a PR where we can collaborate on the details of this? It would also make it more clear what the changes are. I think there are ways to make the API better while still having the same benefits.

 > Less safe API as it's based on Ids

I'm not sure what this means. Could you explain?

**Comment by msiglreith** [comment]
Hey!

> Would you mind putting up a PR where we can collaborate on the details of this? It would also make it more clear what the changes are. 

I will, due to formatting it became quite difficult to review the changes. Beforehand I would like to try to make the changes a bit more incremental in my branch.

> I'm not sure what this means. Could you explain?

Hmm, actually it's not inherently unsafer. Currently a `NodeId` in the branch is just a type alias for `usize` so users could try to address dead or non-existent nodes. Creating a newtype would help to mitigate this issue. Accessing destroyed nodes could be avoided by making it non-`Copy`.  There seem to be some open design questions :)

**Comment by emilsjolander** [comment]
Look forward to the PR! Yea I think we can do a ton on the API design side to make this really nice.

**Comment by msiglreith** [comment]
First draft setup in https://github.com/vislyhq/stretch/pull/37

**Comment by msiglreith** [comment]
Resolved with https://github.com/vislyhq/stretch/pull/37
