### ISSUE TITLE
New API allowing for efficient re-rendering of trees

### ISSUE THREAD

**Issue by emilsjolander** [vislyhq/stretch#18]
I'm currently in the early stages of designing a new API with the goal of making it easier to implement efficient re-rendering of partially updated trees. The idea is to go from todays declarative and immutable API to a more imperative and mutable API to make this possible. 

Today's API is very easy to work with and makes it especially easy to declare larger hierarchies as a single structure. This apposed to creating a node and calling methods on it to set various properties.

```rust 
let style = style::Node {
  flex_direction: style::FlexDirection::Column,
  children: vec![
    style::Node { ..Default::default() },
  ],
  ..Default::default()
};

let layout = compute(style, Size::undefined());
```

However this makes it very difficult to implement efficient re-rendering of partially updated trees. Say for example you make the above `style` a mutable variable, this way you would be able to update its `flex_direction` however because this is just a simple struct field you would also manually have to make the node as dirty. And because `children` is just a regular `Vec` field the children get no pointer to their parent when inserted into a node which makes it impossible to automatically traverse the tree to its root when marking nodes as dirty.

An API which solves the above problems is one which makes use of methods instead of public struct fields.

```rust
let mut style = style::Node::new();
style.set_flex_direction(style::FlexDirection::Column);
style.add_child(style::Node::new());

let layout = compute(style, Size::undefined());
```

With this API we can automatically mark a node as dirty when a setter is called on it, we can also correctly propagate this dirty flag up the tree by saving a parent pointer when adding a child node. The downside of this API is that there is no way to declaratively create static trees. This is mostly an issue for tests which will become much harder to read. For this I propose we add a macro `style::node!`, much like how `vec!` hides the underlying mutable API of `Vec`.

```rust
let style = style::node! {
  flex_direction: style::FlexDirection::Column,
  children: style::node! {},
};
```

**Comment by msiglreith** [comment]
Thanks for the writeup!

The proposal from https://github.com/vislyhq/stretch/issues/17 is rather orthogonal to this one, but I wrote up a small sketch: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6c46face46d5a6667fd7c5bef5a7e9ba
It's more focused on being able to reuse memory and try to solve the `layout::Node` <-> `style::Node` indexing issue.

> which makes it impossible to automatically traverse the tree to its root when marking nodes as dirty.

At which point of the API would the dirty flag be propagated?

I'm still having a bit of struggle to understand how users are usually update their layout tree in production. For example removing the possibility to remove nodes from the tree would allow rather larger simplifications on how to propagate the dirty flag for example.

**Comment by emilsjolander** [comment]
@msiglreith Ah ok! thanks for the sketch.

In my proposal dirty propagation would happen in the set* methods. Removing nodes has to be a supported operation, it perhaps does not need to have equal performance to other operations though. One example would be a pop-over view which is added / removed to a layout based on some even such as a mouse-over hover.

Another way to solve `layout::Node` <-> `style::Node` indexing would be to have a pointer from a `style::Node` to its corresponding `layout::Node`. It already basically has this due to the layout cache.
