### ISSUE TITLE
Is there something like an ID?

### ISSUE THREAD

**Issue by MichaelHoelzl** [vislyhq/stretch#19]
Is there something like an ID?
Or is there a better way to provide information for other objects? To bind the result to a UI widget.

```RUST
let node = Node {
        id: 10,
        size: Size { width: Dimension::Points(100.0), height: Dimension::Points(100.0) },
        justify_content: JustifyContent::Center,

        children: vec![Node {
            id: 11,
            size: Size { width: Dimension::Percent(0.5), height: Dimension::Auto },
            ..Default::default()
        }],

        ..Default::default()
    };
```

```
Node {
    id: 10,
    order: 0,
    size: Size {
        width: 100.0,
        height: 100.0
    },
    location: Point {
        x: 0.0,
        y: 0.0
    },
    children: [
        Node {
            id: 11,
            order: 0,
            size: Size {
                width: 50.0,
                height: 100.0
            },
            location: Point {
                x: 25.0,
                y: 0.0
            },
            children: []
        }
    ]
}
```

**Comment by emilsjolander** [comment]
The way we are currently managing this is to have a mirrored tree of UI widgets and then just iterating over the two trees simultaneously and transferring layout values. This isn't great though and something that I ideally want to fix with an API re-design included here https://github.com/vislyhq/stretch/issues/18. I would like to allow UI nodes to contain a reference to the stretch node. Not quite sure how to best do this though, maybe make use of `RC` instead of having the stretch tree be the single owner of each node.

If you have a better idea it would be super helpful to have help mock out an API to solve this.

**Comment by MichaelHoelzl** [comment]
I think `RC` is a good idea, but I'm not sure which direction. 
A reference from `Stretch::Node` to Widget.
Or place a widget reference in the `Stretch::Node`.

Maybe a something like public RenderWidget trait?
```RUST
pub trait RenderWidget {}

impl RenderWidget for UIButton{} 
impl RenderWidget for UIPicture{} 
impl RenderWidget for UITreeView{} 
```
Then you can bind the widget to a node by reference.
```RUST
RC<RefCell<RenderWidget>>
```
I think iterating over the two trees is the worst way, maybe some ways need to be tried to find the best one.

**Comment by emilsjolander** [comment]
I agree iterating over both trees is bad. What I'm going for is having a `RC<RefCell<Node>>` inside of the `RenderWidget`. That way the `RenderWidget` would be able to read and write to the `Node`. There should not be any reason for the `Node` to have a reference to a `RenderWidget`. Or am I missing something?

**Comment by MichaelHoelzl** [comment]
A `RC<RefCell<Node>>` inside of the RenderWidget is a good way.
What could the way to build the tree look like? Something like this?

```RUST
let widget = RenderWidget {
	node: RC::new(RefCell::new(Node {
		size: Size { width: Dimension::Percent(0.5), height: Dimension::Auto },
		..Default::default()
	})),
	color: Color::rgb(255,0,0)
};


let node = Node {
	id: 10,
	size: Size { width: Dimension::Points(100.0), height: Dimension::Points(100.0) },
	justify_content: JustifyContent::Center,

	children: vec![widget.node.clone()],

	..Default::default()
};
```

**Comment by emilsjolander** [comment]
Recent refactor makes use of `Rc<RefCell<>>` internally as well as adding mutable api to the node interface. This enables you to embed `Node` as a private member of `RenderWidget` which would mirror the widget tree. 

So your code may look something like this (hastily written to get the general idea across, does not compile).

```rust
struct RenderWidget {
    node: stretch::node::Node,
    children: Vec<RenderWidget>,
}

impl RenderWidget {
    fn add_child(&mut self, widget: RenderWidget) {
        self.node.add_child(&widget.child);
        self.children.push(widget);
    }

    fn compute_layout(&mut self, size: stretch::geometry::Size<stretch::number::Number>) {
        let layout = node.compute_layout(size).unwrap();
        self.apply_layout(layout);
    }

    fn apply_layout(&mut self, layout: stretch::result::Layout) {
        // TODO somehow apply layout

        for i in 0..self.children.len() {
            let child = self.children[i];
            let childLayout = layout.children[i];
            child.apply_layout(childLayout);
        }
    }
}
```

**Comment by emilsjolander** [comment]
We still don't have the concept of ID. I'm not against adding it if there is good reason for it but I am not yet convinced that ID is not something that is better added by a user-space wrapper object. Happy to open that discussion back up.
