### ISSUE TITLE
Interfacing with other languages

### ISSUE THREAD

**Issue by pablosichert** [vislyhq/stretch#3]
Hey there!

First of all: Awesome project.

Just some quick questions:
- do you plan to expose methods via the C ABI or should that be done in a separate project?
- do you plan on having bindings to other languages / frameworks in this repository?

(Backstory: I'm working on a React-like [framework](https://github.com/PabloSichert/Sx) for Swift and I'm looking for a solid stand-alone implementation of flexbox.)

I'd be happy to help here where I can!

**Comment by emilsjolander** [comment]
Hey there! Sorry it took so long to see this, as the project is so new I didn't expect to see any issues yet haha. I've just updated the readme with goals and specific areas where we would be extra excited about contributions. 

C ABI is definitely on the list as goals include Android and iOS Interop, both of which will be much easier by going via a C ABI. This will be core to the project so should live in the core repo and not as a separate project imho.

**Comment by pablosichert** [comment]
Haha, no problem - I figured out you were still working on setting up the project.

I got some work in progress for the C bindings, I'll open a PR shortly
