### ISSUE TITLE
Proposition: Conditionally implement Serialize/Deserialize traits from serde crate for Style relates structs and enums

### ISSUE THREAD

**Issue by yawor** [vislyhq/stretch#48]
Hi,

It would be nice to see stretch implement (as a non-default feature) Serialize and Deserialize traits from Serde crate, so a program could load styles from a JSON or YAML file for example or serialize them.
For now, I've implemented this using Serde's "remote" feature, which allows to overcome Rust's orphan rule for implementing external crate's traits for other external create's types. This works but it's not very robust solution (I've had to make a copy of all Style related structs and enums and modify then according to Serde's documentation).
I can prepare a PR for this if there no objection from the authors.

**Comment by yawor** [comment]
OK, I've went ahead anyway and already prepared a PR #49. Feature name is `serde`. When enabled, it affects only Style related structs and enums.

**Comment by emilsjolander** [comment]
Agreed! Sorry for the delayed response, I've merged your PR. Really good stuff. Thank you!
